"use strict";
let num1 = 5;
let num2 = 10;
console.log("Is num1 is equal to num2?");
console.log(num1 == num2);
console.log("Is num1 is greater than num2?");
console.log(num1 > num2);
console.log("Is num2 is equal to num1?");
console.log(num2 == num1);
console.log("Is num2 less than num1?");
console.log(num2 < num1);
console.log("Is num2 is equal to 5?");
console.log(num2 == 5);
console.log("Is num1 is equal to 5?");
console.log(num1 == 5);
console.log("Is num2 is greater than num1?");
console.log(num2 > num1);
console.log("Is num2 is not equal to num1?");
console.log(num2 != num1);
console.log("Is num1 is not equal to num2?");
console.log(num1 != num2);
console.log("Is num1 is less than num2?");
console.log(num1 < num2);
